server:
  port: 9061

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 67069480789-opbiv19f8429jqji57qv0r8beg1fcr53.apps.googleusercontent.com
            clientSecret: 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
          #          facebook:
          #            client-id: 1108041866346884
          #            client-secret: f52f8eaab7cdd0272d37ab89e0335be1
          #          kakao:
          #            client-id: fa84d469d8038b6a422d1f9b2b6f9067
          #            client-secert: RuubX7J4HuhrekWplEeu2FnlSMiCftHH
          #            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          #            authorization-grant-type: authorization_code
          #            client-name: kakao
          naver:
            client-id: bkdZjYp4EfmqIkZaEtqi
            client-secret: YLHoiLkdSy
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: naver

        provider:
          #          kakao:
          #            authorization-uri: https://kauth.kakao.com/oauth/authorize
          #            token-uri: https://kauth.kakao.com/oauth/token
          #            user-info-uri: https://kapi.kakao.com/v2/user/me
          #            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response